spring.application.name=simulation-engine

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/stockdb
spring.datasource.username=postgres
spring.datasource.password=wissen
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

app.price.update.interval=1000
app.snapshot.interval=30000

logging.level.org.springframework=INFO
logging.level.com.stock=DEBUG