spring.application.name=share-bazar-backend

# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/studentdb
spring.datasource.username=postgres
spring.datasource.password=josh@reb1

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SERVER
server.port=8084

jwt.secret=MyUltraSecureSecretKeyThatIsAtLeast32BytesLongForHS256!!!
jwt.expiration=8640000000

# Eureka Server URL
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Register with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true