spring.application.name=exchanger-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.yojehjkoshmksavjmewi&password=0V0MjR2qU8CAxiw3
spring.datasource.username=postgres.yojehjkoshmksavjmewi
spring.datasource.password=0V0MjR2qU8CAxiw3
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl