spring.application.name=admin-service
server.port=8082

# ✅ TEMP DB (H2 - NO POSTGRES REQUIRED)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# OPTIONAL (H2 Console for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console