spring.application.name=orderService


# PostgreSQL DB Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/transcaion
spring.datasource.username=postgres
spring.datasource.password=wissen

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Show SQL (optional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port = 8086
eureka.client.enabled=false
spring.cloud.discovery.enabled=false